classification: company_oomlout
color: ''
description_extra: ''
description_main: hardware_screw_countersunk_m3_black_hex_head_version_1
id: company_oomlout_product_prototyping_tin_hardware_screw_countersunk_m3_black_hex_head_version_1_oomlout_ptcs3bhv1
manufacturer: oomlout
part_number: ptcs3bhv1
size: prototyping_tin
type: product
